#!/usr/bin/env python3
"""
Create consolidated summary files for story content.

Instead of creating hundreds of individual files, this script creates just 5 consolidated files:
- all_characters.md (all character files combined)
- all_locations.md (all location files combined)
- all_chapters.md (all chapter files combined)
- all_core.md (all core files combined)
- all_worldbuilding.md (all worldbuilding files combined)

Each consolidated file includes clear section separators and source attribution.
"""

import os
from pathlib import Path
from typing import List, Tuple

def create_summaries_directory(base_path: Path) -> Path:
    """Create the summaries directory if it doesn't exist."""
    summaries_dir = base_path / "summaries"
    summaries_dir.mkdir(exist_ok=True)
    return summaries_dir

def create_section_separator(title: str, source_path: str) -> str:
    """Create a visual separator for a new section."""
    return f"""
========================================
## {title}
========================================
Source: {source_path}

"""

def create_file_header(file_type: str, count: int) -> str:
    """Create the header for each consolidated file."""
    return f"""# ALL {file_type.upper()}

This file contains all {file_type} content from the MemoryQuill story, consolidated for easier upload and review.
Total sections included: {count}

Generated by create_consolidated_summaries.py

"""

def consolidate_characters(characters_dir: Path, output_file: Path) -> int:
    """Consolidate all character files into a single file."""
    if not characters_dir.exists():
        return 0

    sections = []
    section_count = 0

    # Get all character directories (excluding templates)
    char_dirs = [d for d in characters_dir.iterdir() if d.is_dir() and "template" not in d.name.lower()]
    char_dirs.sort()  # Sort alphabetically

    for char_dir in char_dirs:
        char_name = char_dir.name.replace('-', ' ').title()

        # Get all markdown files in this character directory
        md_files = list(char_dir.glob("*.md"))
        md_files.sort()  # Sort alphabetically

        for md_file in md_files:
            section_name = md_file.stem.replace('-', ' ').title()
            title = f"CHARACTER: {char_name} - {section_name}"
            source_path = str(md_file.relative_to(characters_dir.parent))

            # Read the file content
            try:
                content = md_file.read_text(encoding='utf-8')
                sections.append(create_section_separator(title, source_path) + content)
                section_count += 1
            except Exception as e:
                print(f"Warning: Could not read {md_file}: {e}")

    # Write consolidated file
    if sections:
        header = create_file_header("Characters", section_count)
        output_file.write_text(header + "\n".join(sections), encoding='utf-8')

    return section_count

def consolidate_locations(locations_dir: Path, output_file: Path) -> int:
    """Consolidate all location files into a single file."""
    if not locations_dir.exists():
        return 0

    sections = []
    section_count = 0

    # Get all location directories (excluding templates)
    loc_dirs = [d for d in locations_dir.iterdir() if d.is_dir() and "template" not in d.name.lower()]
    loc_dirs.sort()  # Sort alphabetically

    for loc_dir in loc_dirs:
        loc_name = loc_dir.name.replace('-', ' ').title()

        # Get all markdown files in this location directory
        md_files = list(loc_dir.glob("*.md"))
        md_files.sort()  # Sort alphabetically

        for md_file in md_files:
            section_name = md_file.stem.replace('-', ' ').title()
            title = f"LOCATION: {loc_name} - {section_name}"
            source_path = str(md_file.relative_to(locations_dir.parent))

            # Read the file content
            try:
                content = md_file.read_text(encoding='utf-8')
                sections.append(create_section_separator(title, source_path) + content)
                section_count += 1
            except Exception as e:
                print(f"Warning: Could not read {md_file}: {e}")

    # Write consolidated file
    if sections:
        header = create_file_header("Locations", section_count)
        output_file.write_text(header + "\n".join(sections), encoding='utf-8')

    return section_count

def consolidate_chapters(chapters_dir: Path, output_file: Path) -> int:
    """Consolidate all chapter files into a single file."""
    if not chapters_dir.exists():
        return 0

    sections = []
    section_count = 0

    # Get all markdown files recursively, but skip scratch/template directories
    all_md_files = []
    for md_file in chapters_dir.rglob("*.md"):
        # Skip files in scratch, template, or draft directories unless they're important
        path_str = str(md_file).lower()
        if any(skip in path_str for skip in ["template", "scratch"]):
            continue
        all_md_files.append(md_file)

    # Sort by path for consistent ordering
    all_md_files.sort(key=lambda x: str(x))

    for md_file in all_md_files:
        # Create a descriptive title based on the file path
        if md_file.parent == chapters_dir:
            # File directly in chapters directory
            chapter_name = md_file.stem
        else:
            # File in a subdirectory
            chapter_name = md_file.parent.name
            if md_file.stem != "content":
                chapter_name += f" ({md_file.stem})"

        title = f"CHAPTER: {chapter_name.replace('-', ' ').title()}"
        source_path = str(md_file.relative_to(chapters_dir.parent))

        # Read the file content
        try:
            content = md_file.read_text(encoding='utf-8')
            sections.append(create_section_separator(title, source_path) + content)
            section_count += 1
        except Exception as e:
            print(f"Warning: Could not read {md_file}: {e}")

    # Write consolidated file
    if sections:
        header = create_file_header("Chapters", section_count)
        output_file.write_text(header + "\n".join(sections), encoding='utf-8')

    return section_count

def consolidate_core(core_dir: Path, output_file: Path) -> int:
    """Consolidate all core files into a single file."""
    if not core_dir.exists():
        return 0

    sections = []
    section_count = 0

    # Get all markdown files in core directory
    md_files = list(core_dir.glob("*.md"))
    md_files.sort()  # Sort alphabetically

    for md_file in md_files:
        title = f"CORE: {md_file.stem.replace('-', ' ').title()}"
        source_path = str(md_file.relative_to(core_dir.parent))

        # Read the file content
        try:
            content = md_file.read_text(encoding='utf-8')
            sections.append(create_section_separator(title, source_path) + content)
            section_count += 1
        except Exception as e:
            print(f"Warning: Could not read {md_file}: {e}")

    # Write consolidated file
    if sections:
        header = create_file_header("Core", section_count)
        output_file.write_text(header + "\n".join(sections), encoding='utf-8')

    return section_count

def consolidate_worldbuilding(worldbuilding_dir: Path, output_file: Path) -> int:
    """Consolidate all worldbuilding files into a single file."""
    if not worldbuilding_dir.exists():
        return 0

    sections = []
    section_count = 0

    # Get all markdown files in worldbuilding directory
    md_files = list(worldbuilding_dir.glob("*.md"))
    md_files.sort()  # Sort alphabetically

    for md_file in md_files:
        title = f"WORLDBUILDING: {md_file.stem.replace('-', ' ').title()}"
        source_path = str(md_file.relative_to(worldbuilding_dir.parent))

        # Read the file content
        try:
            content = md_file.read_text(encoding='utf-8')
            sections.append(create_section_separator(title, source_path) + content)
            section_count += 1
        except Exception as e:
            print(f"Warning: Could not read {md_file}: {e}")

    # Write consolidated file
    if sections:
        header = create_file_header("Worldbuilding", section_count)
        output_file.write_text(header + "\n".join(sections), encoding='utf-8')

    return section_count

def main():
    """Main function to create consolidated summary files."""
    # Get the directory where this script is located
    base_path = Path(__file__).parent

    # Create summaries directory
    summaries_dir = create_summaries_directory(base_path)
    print(f"Created summaries directory: {summaries_dir}")

    # Define source directories
    characters_dir = base_path / "characters"
    locations_dir = base_path / "locations"
    chapters_dir = base_path / "chapters"
    core_dir = base_path / "core"
    worldbuilding_dir = base_path / "worldbuilding"

    # Define output files
    output_files = {
        "characters": summaries_dir / "all_characters.md",
        "locations": summaries_dir / "all_locations.md",
        "chapters": summaries_dir / "all_chapters.md",
        "core": summaries_dir / "all_core.md",
        "worldbuilding": summaries_dir / "all_worldbuilding.md"
    }

    total_sections = 0

    # Consolidate each category
    print("\nConsolidating characters...")
    char_count = consolidate_characters(characters_dir, output_files["characters"])
    print(f"Created all_characters.md with {char_count} sections")
    total_sections += char_count

    print("\nConsolidating locations...")
    loc_count = consolidate_locations(locations_dir, output_files["locations"])
    print(f"Created all_locations.md with {loc_count} sections")
    total_sections += loc_count

    print("\nConsolidating chapters...")
    chapter_count = consolidate_chapters(chapters_dir, output_files["chapters"])
    print(f"Created all_chapters.md with {chapter_count} sections")
    total_sections += chapter_count

    print("\nConsolidating core...")
    core_count = consolidate_core(core_dir, output_files["core"])
    print(f"Created all_core.md with {core_count} sections")
    total_sections += core_count

    print("\nConsolidating worldbuilding...")
    worldbuilding_count = consolidate_worldbuilding(worldbuilding_dir, output_files["worldbuilding"])
    print(f"Created all_worldbuilding.md with {worldbuilding_count} sections")
    total_sections += worldbuilding_count

    # Summary
    print(f"\n" + "="*60)
    print(f"CONSOLIDATION COMPLETE")
    print(f"="*60)
    print(f"Total sections consolidated: {total_sections}")
    print(f"Output files created: 5")
    print(f"\nFiles created in {summaries_dir}:")
    for file_type, file_path in output_files.items():
        if file_path.exists():
            size = file_path.stat().st_size
            print(f"  {file_path.name}: {size:,} bytes")
        else:
            print(f"  {file_path.name}: Not created (no content found)")

if __name__ == "__main__":
    main()